aum = int(input('digite o numero para ver sua tabuada: '))
print('='*12)
print('{} x {} = {}'.format(aum, 1, aum*1))
print('{} x {} = {}'.format(aum, 2, aum*2))
print('{} x {} = {}'.format(aum, 3, aum*3))
print('{} x {} = {}'.format(aum, 4, aum*4))
print('{} x {} = {}'.format(aum, 5, aum*5))
print('{} x {} = {}'.format(aum, 6, aum*6))
print('{} x {} = {}'.format(aum, 7, aum*7))
print('{} x {} = {}'.format(aum, 8, aum*8))
print('{} x {} = {}'.format(aum, 9, aum*9))
print('{} x {} = {}'.format(aum, 10, aum*10))
print('='*12)

