a = input('digite algo: ')
print('o tipo primitivo desse valor é ', type (a))
print('só tem espaços? ', a.isspace())
print('é número? ', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print('é alfanumérico? ', a.isalnum())
print('esta maiuscula? ', a.isupper())
print('esta minuscula? ', a.islower())
print('esta capitalizada? ', a.istitle())
