nome = str(input('qual é seu nome completo:')).strip()
print('analisando seu nome...')
print('seu nome em leitra maiuscula é {}.'.format(nome.upper()))
print('seu nome em letra minuscula é {}'.format(nome.lower()))
print('seu nome ao todo tem {} letras'.format(len(nome) - nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ' )))